### ISSUE TITLE
Compilation error in the recent 2.5.6

### ISSUE THREAD

**Issue by admzzz** [WizTeam/WizQTClient#483]
[ 65%] Building CXX object src/CMakeFiles/WizNote.dir/sync/WizKMSync.cpp.o
In file included from /home/admz/build/WizQTClient-2.5.6/src/sync/WizKMSync.cpp:1:0:
`/home/admz/build/WizQTClient-2.5.6/src/sync/WizKMSync.h:100:12: error: field 'm_mutex' has incomplete type 'QMutex'`
     QMutex m_mutex;
            ^~~~~~~
In file included from /opt/qt58/include/QtCore/QWaitCondition:1:0,
                 from /home/admz/build/WizQTClient-2.5.6/src/sync/WizKMSync.h:6,
                 from /home/admz/build/WizQTClient-2.5.6/src/sync/WizKMSync.cpp:1:
/opt/qt58/include/QtCore/qwaitcondition.h:53:7: note: forward declaration of 'class QMutex'
 class QMutex;
       ^~~~~~
src/CMakeFiles/WizNote.dir/build.make:1233: recipe for target 'src/CMakeFiles/WizNote.dir/sync/WizKMSync.cpp.o' failed
make[2]: *** [src/CMakeFiles/WizNote.dir/sync/WizKMSync.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/WizNote.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:254: recipe for target 'src/CMakeFiles/WizNote.dir/all' failed
Makefile:129: recipe for target 'all' failed
12:53:14: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project Project (kit: Desktop)
When executing step "CMake Build"
12:53:14: Elapsed time: 04:24.

**Comment by KANGOD** [comment]
同样的错误。

环境：
Ubuntu 14.04.5 LTS
Qt Creator 4.3.1
  Based on Qt 5.9.1 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)

日志：
16:28:06: Running steps for project Project...
16:28:06: Starting: "/usr/bin/cmake" --build . --target all
[ 38%] Built target cryptlib
[ 39%] Automoc for target quazip
[ 39%] Built target quazip_automoc
[ 43%] Built target quazip
[ 43%] Automoc for target WizNote
[ 43%] Built target WizNote_automoc
[ 43%] Building CXX object src/CMakeFiles/WizNote.dir/sync/WizKMSync.cpp.o
In file included from /home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:1:0:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.h:100:12: error: field ‘m_mutex’ has incomplete type
     QMutex m_mutex;
            ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘virtual void WizKMSyncThread::run()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:152:9: error: ‘m_mutex’ was not declared in this scope
         m_mutex.lock();
         ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘void WizKMSyncThread::on_timerOut()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:182:5: error: ‘m_mutex’ was not declared in this scope
     m_mutex.lock();
     ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘void WizKMSyncThread::startSyncAll(bool)’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:189:5: error: ‘m_mutex’ was not declared in this scope
     m_mutex.lock();
     ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘bool WizKMSyncThread::downloadMesages()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:385:26: error: ‘m_mutex’ was not declared in this scope
     QMutexLocker locker(&m_mutex);
                          ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘bool WizKMSyncThread::needQuickSync()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:418:26: error: ‘m_mutex’ was not declared in this scope
     QMutexLocker locker(&m_mutex);
                          ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘bool WizKMSyncThread::needDownloadMessage()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:436:26: error: ‘m_mutex’ was not declared in this scope
     QMutexLocker locker(&m_mutex);
                          ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘void WizKMSyncThread::stopSync()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:453:9: error: ‘m_mutex’ was not declared in this scope
         m_mutex.lock();
         ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘void WizKMSyncThread::addQuickSyncKb(const QString&)’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:466:26: error: ‘m_mutex’ was not declared in this scope
     QMutexLocker locker(&m_mutex);
                          ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘void WizKMSyncThread::quickDownloadMesages()’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:484:26: error: ‘m_mutex’ was not declared in this scope
     QMutexLocker locker(&m_mutex);
                          ^
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp: In member function ‘bool WizKMSyncThread::peekQuickSyncKb(QString&)’:
/home/weekend/Programs/installFromSource/WizQTClient/src/sync/WizKMSync.cpp:492:26: error: ‘m_mutex’ was not declared in this scope
     QMutexLocker locker(&m_mutex);
                          ^
make[2]: *** [src/CMakeFiles/WizNote.dir/sync/WizKMSync.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/WizNote.dir/all] Error 2
make: *** [all] Error 2
16:28:08: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project Project (kit: Desktop Qt 5.9.1 GCC 64bit)
The kit Desktop Qt 5.9.1 GCC 64bit has configuration issues which might be the root cause for this problem.
When executing step "CMake Build"
16:28:08: Elapsed time: 00:02.

**Comment by windilt** [comment]
same error...

**Comment by BSCCO** [comment]
same error, too……

**Comment by gring000** [comment]
错误是WizKMSync.h文件中没有include m_mutex,
因此在WizKMSync.h中加入一行
```
#include <qmutex.h>
```
重新载入文件再编译就好了。

**Comment by admzzz** [comment]
thanks, gring000.

**Comment by fengluoye** [comment]
thinks,gring0000.找了好多地方，就这个答案是靠谱的。非常感谢！
